project:
  type: website
  output-dir: docs  # Store rendered website in the docs folder

website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: life-gdp.qmd
        text: Life Expectancy and GDP per Capita
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


